[default_session]
startup_command  = "nvim"

[[session]]
name = "󱥸 dotfiles"
path = "~/.dotfiles"
startup_command = "nvim -c ':Oil'"

[[session]]
name = " nvim config"
path = "~/.dotfiles/nvim"
startup_command = "nvim -c ':Config'"

[[session]]
name = " zsh config"
path = "~/.dotfiles/zsh/.config/zsh"
startup_command = "nvim ~/.dotfiles/zsh/.config/zsh/.zshrc"

[[session]]
name = " tmux config"
path = "~/.dotfiles/tmux/.config/tmux"
startup_command = "nvim ~/.dotfiles/tmux/.config/tmux/tmux.conf"

