if type grc-rs > /dev/null; then
    alias blkid='/home/echo/.cargo/bin/grc-rs blkid';
    alias curl='/home/echo/.cargo/bin/grc-rs curl';
    alias df='/home/echo/.cargo/bin/grc-rs df';
    alias diff='/home/echo/.cargo/bin/grc-rs diff';
    alias dig='/home/echo/.cargo/bin/grc-rs dig';
    alias docker='/home/echo/.cargo/bin/grc-rs docker';
    alias du='/home/echo/.cargo/bin/grc-rs du';
    alias env='/home/echo/.cargo/bin/grc-rs env';
    alias fdisk='/home/echo/.cargo/bin/grc-rs fdisk';
    alias findmnt='/home/echo/.cargo/bin/grc-rs findmnt';
    alias free='/home/echo/.cargo/bin/grc-rs free';
    alias gcc='/home/echo/.cargo/bin/grc-rs gcc';
    alias getfacl='/home/echo/.cargo/bin/grc-rs getfacl';
    alias id='/home/echo/.cargo/bin/grc-rs id';
    alias ip='/home/echo/.cargo/bin/grc-rs ip';
    alias iptables='/home/echo/.cargo/bin/grc-rs iptables';
    alias iwconfig='/home/echo/.cargo/bin/grc-rs iwconfig';
    alias kubectl='/home/echo/.cargo/bin/grc-rs kubectl';
    alias last='/home/echo/.cargo/bin/grc-rs last';
    alias lsattr='/home/echo/.cargo/bin/grc-rs lsattr';
    alias lsblk='/home/echo/.cargo/bin/grc-rs lsblk';
    alias lsmod='/home/echo/.cargo/bin/grc-rs lsmod';
    alias lsof='/home/echo/.cargo/bin/grc-rs lsof';
    alias lspci='/home/echo/.cargo/bin/grc-rs lspci';
    alias mount='/home/echo/.cargo/bin/grc-rs mount';
    alias ping='/home/echo/.cargo/bin/grc-rs ping';
    alias ps='/home/echo/.cargo/bin/grc-rs ps';
    alias pv='/home/echo/.cargo/bin/grc-rs pv';
    alias ss='/home/echo/.cargo/bin/grc-rs ss';
    alias stat='/home/echo/.cargo/bin/grc-rs stat';
    alias sysctl='/home/echo/.cargo/bin/grc-rs sysctl';
    alias systemctl='/home/echo/.cargo/bin/grc-rs systemctl';
    alias tcpdump='/home/echo/.cargo/bin/grc-rs tcpdump';
    alias tune2fs='/home/echo/.cargo/bin/grc-rs tune2fs';
    alias uptime='/home/echo/.cargo/bin/grc-rs uptime';
    alias vmstat='/home/echo/.cargo/bin/grc-rs vmstat';
    alias docker='/home/echo/.cargo/bin/grc-rs docker';
    alias go='/home/echo/.cargo/bin/grc-rs go';
    alias iostat='/home/echo/.cargo/bin/grc-rs iostat';
    alias lsusb='/home/echo/.cargo/bin/grc-rs lsusb';
else
    echo "grc-rs missing."
fi
