#!/usr/bin/env bash
git submodule init
git submodule update

# Set DEVMODE
if [ -f "$HOME/.config/devmode" ]; then
    DEVMODE=1
fi

# Bootstrap some basic directories
if [ ! -d "$HOME/.local" ]; then
    mkdir "$HOME/.local"
fi

if [ ! -d "$HOME/.local/share" ]; then
    mkdir "$HOME/.local/share"
fi

ignore_directories=("metadata/" "firefox/" "windows/" "nix/" "glzr/")

for i in */; do
    if [[ " ${ignore_directories[@]} " =~ " $i " ]]; then
        continue
    fi
    stow -v -R "$i";
done

# Install tmux plugin manager if it's not installed
if [[ ! -d "$HOME/.config/tmux/plugins/tpm" ]]; then
    git clone https://github.com/tmux-plugins/tpm $HOME/.config/tmux/plugins/tpm
fi

if type code 2>/dev/null; then
    cat "vscode/.config/Code/extensions.txt" | xargs -L 1 code --install-extension
fi

# Install neovim plugins
nvim --headless +"Lazy! restore" +qa

# Install treesitter plugins
nvim --headless +TSUpdate +qa
