#!/bin/bash
# Select the Nerd Font from https://www.nerdfonts.com/font-downloads
# Testing with ShellCheck

FONT_DIR="$HOME/.local/share/fonts"

echo "[-] Download The Nerd fonts [-]"
echo "#######################"
echo "Select Nerd Font"
fons_list=("AtkinsonHyperlegibleMono" "JetBrainsMono" "Iosevka" "NerdFontsSymbolsOnly" "OpenDyslexic" "Terminus")
for font_name in "${fons_list[@]}";
 do

    if [ -n "$font_name" ]; then

        # Check if font is already installed
        if [ -d "$FONT_DIR/$font_name" ]; then
            echo "Font $font_name is already installed, skipping..."
            continue
        fi

        echo "Starting download $font_name nerd font"

        if [ "$(command -v curl)" ]; then
            echo "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/$font_name.zip"
            curl -OL "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/$font_name.zip"
            echo "creating fonts folder: $FONT_DIR"
            mkdir -p  "$FONT_DIR"
            echo "unzip the $font_name.zip"
            unzip "$font_name.zip" -d "$FONT_DIR/$font_name/"
            fc-cache -fv
            echo "Cleaning up $font_name.zip"
            rm "$font_name.zip"
            echo "done!"

        elif [ "$(command -v wget)" ]; then
            echo "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/$font_name.zip"
            wget "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/$font_name.zip"
            echo "creating fonts folder: $FONT_DIR"
            mkdir -p  "$FONT_DIR"
            echo "unzip the $font_name.zip"
            unzip "$font_name.zip" -d "$FONT_DIR/$font_name/"
            fc-cache -fv
            echo "Cleaning up $font_name.zip"
            rm "$font_name.zip"
            echo "done!"

        else

            echo "We cannot find the curl and wget command. First, install the curl and wget command, one of them."
            break

        fi

    else

        echo "Select the vaild $font_name nerd Font, just type number"
        continue;

    fi
done
