#!/bin/sh

echo "Updating base16-shell"
git subtree pull --prefix base16-shell/.config/base16-shell git@github.com:chriskempson/base16-shell.git master

echo "Updating fzf-tab"
git subtree pull --prefix zsh/.config/zsh/plugins/fzf-tab git@github.com:Aloxaf/fzf-tab.git master

