# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/f1dba6d1-6648-400a-ba29-25a5f699e9ea";
    fsType = "ext4";
  };

  boot.extraModulePackages = with config.boot.kernelPackages; [
    v4l2loopback
  ];
  boot.extraModprobeConfig = ''
    options v4l2loopback devices=1 video_nr=1 card_label="OBS Cam" exclusive_caps=1
  '';

  services.udev.extraRules = ''
    # Grant access to GoXLRMin device over USB
    SUBSYSTEM=="usb", ATTR{idVendor}=="1220", ATTR{idProduct}=="8fe4", MODE="0660", GROUP="audio"
  '';

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/95AE-6CA5";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/2d7c255f-2e84-4127-9205-12c2086b8a34";
    fsType = "btrfs";
  };

  fileSystems."/home/echo/projects" = {
    device = "/dev/disk/by-uuid/1816d42e-528e-479b-8f16-8e5073cd961a";
    fsType = "btrfs";
    options = [
      "noauto"
      "nofail"
      "x-systemd.automount"
      "x-systemd.device-timeout=10"
      "subvol=/projects"
    ];
  };

  fileSystems."/home/echo/games" = {
    device = "/dev/disk/by-uuid/1816d42e-528e-479b-8f16-8e5073cd961a";
    fsType = "btrfs";
    options = [
      "noauto"
      "nofail"
      "x-systemd.automount"
      "x-systemd.device-timeout=10"
      "subvol=/games"
    ];
  };

  fileSystems."/mnt/c" = {
    device = "/dev/disk/by-partuuid/117889dc-9ffd-4b53-bb17-5f047ef3f8cb";
    fsType = "ntfs";
    options = [
      "ro"
    ];
  };

  fileSystems."/mnt/mac-drive" = {
    device = "/dev/disk/by-partuuid/c3ae2008-d9e8-46cc-9e78-477b123eab42";
    fsType = "ntfs";
    options = [
      "ro"
    ];
  };

  fileSystems."/mnt/fast-games" = {
    device = "/dev/disk/by-partuuid/15e5c54c-86c7-11ef-82ee-b89a2a7252ad";
    fsType = "ntfs";
    options = [
      "ro"
    ];
  };

  fileSystems."/mnt/slow-games" = {
    device = "/dev/disk/by-partuuid/29f1b79f-fcfd-11ee-8291-244bfe48601b";
    fsType = "ntfs";
    options = [
      "ro"
    ];
  };

  fileSystems."/mnt/slow-games-and-docs" = {
    device = "/dev/disk/by-partuuid/913be62b-79c5-40ab-9836-3a0ce0a3beff";
    fsType = "ntfs";
    options = [
      "ro"
    ];
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.graphics = {
    enable = true;
  };

  services.xserver = {
    displayManager.setupCommands = "${pkgs.xorg.xrandr}/bin/xrandr --output DP-0 --mode 2560x1440 --pos 0x0 --rotate left --output HDMI-0 --mode 1920x1080 --pos 1440x1952 --rotate normal --output DP-4 --primary --mode 2560x1440 --pos 1440x512 --rotate normal";
  };

  hardware.openrazer = {
    users = ["echo"];
    enable = true;
  };
  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
  };
}
