#!/usr/bin/env bash

TEMP_DIR=$(mktemp -d /tmp/secrets-export.XXXXXX)
FILENAME=$1

mkdir -v $TEMP_DIR
chmod -v 700 $TEMP_DIR
mkdir -v $TEMP_DIR/secrets
mkdir -v $TEMP_DIR/secrets/gnupg
mkdir -v $TEMP_DIR/secrets/ssh

# Export GNUPG keys to export dir
gpg --export-secret-keys --armor > "${TEMP_DIR}/secrets/gnupg/all-private-keys.asc"

# Copy private SSH keys
cp -av "$HOME/.ssh/id"* "${TEMP_DIR}/secrets/ssh"

# Chmod everythign to be owner only
chmod -v 600 "${TEMP_DIR}/secrets/ssh/"*
chmod -v 600 "${TEMP_DIR}/secrets/gnupg/"*

# Create the tarball
cd "${TEMP_DIR}"
tar cvfz "${HOME}/${FILENAME}.tar.gz" "./secrets"
cd -

# Remove the tmpdir
rm -rfv "${TEMP_DIR}"
