#!/usr/bin/env bash

NAME=$1
TEMP_DIR=$(mktemp -d /tmp/secret-restore-XXXXXXX)

cd $TEMP_DIR
tar xvfz "$NAME" 
# Restore ssh keys
cp -avi "${TEMP_DIR}/secrets/ssh/"* "${HOME}/.ssh/"

# Restore gnupg keys
gpg --import "${TEMP_DIR}/secrets/gnupg/all-private-keys.asc"

cd -
rm -rfv $TEMP_DIR
