return {
    {
        "williamboman/mason.nvim",
        enabled = true,
        cond = os.getenv("DEVMODE") ~= nil,
        event = { "BufReadPost", "BufNewFile" },
        cmd = {
            "Mason",
            "MasonInstall",
            "MasonLog",
            "MasonUninstall",
            "MasonUpdate",
        },
        opts = true,
    },
    {
        "williamboman/mason-lspconfig.nvim",
        enabled = true,
        cond = os.getenv("DEVMODE") ~= nil,
        event = { "BufReadPost", "BufNewFile" },
        opts = {
            ensure_installed = {
                "ansiblels",
                "bashls",
                "cssls",
                "cssmodules_ls",
                "docker_compose_language_service",
                "dockerls",
                "emmet_language_server",
                "eslint",
                "html",
                "jsonls",
                "lua_ls",
                "perlnavigator",
                "pyright",
                "ruff",
                "rust_analyzer",
                "sqlls",
                "tailwindcss",
                "tinymist",
                "ts_ls",
                "vimls",
                "yamlls",
            },
        },
    },
    {
        "WhoIsSethDaniel/mason-tool-installer.nvim",
        enabled = true,
        cond = os.getenv("DEVMODE") ~= nil,
        event = { "BufReadPost", "BufNewFile" },
        opts = {
            ensure_installed = {
                "prettierd",
                "djlint",
                "stylua",
                "black",
                "flake8",
            },
        },
    },
}
