return {
    {
        "williamboman/mason.nvim",
        cond = os.getenv("DEVMODE") ~= nil,
        opts = true,
    },
    {
        "williamboman/mason-lspconfig.nvim",
        version = "1.x.x",
        cond = os.getenv("DEVMODE") ~= nil,
        opts = {
            ensure_installed = {
                "ansiblels",
                "basedpyright",
                "bashls",
                "cssls",
                "cssmodules_ls",
                "docker_compose_language_service",
                "dockerls",
                "emmet_language_server",
                "eslint",
                "html",
                "jsonls",
                "lua_ls",
                "perlnavigator",
                "pyright",
                "ruff",
                "rust_analyzer",
                "sqlls",
                "tailwindcss",
                "ts_ls",
                "vimls",
                "yamlls",
            },
        },
    },
    {
        "WhoIsSethDaniel/mason-tool-installer.nvim",
        cond = os.getenv("DEVMODE") ~= nil,
        commit = "1255518cb067e038a4755f5cb3e980f79b6ab89c",
        opts = {
            ensure_installed = {
                "prettierd",
                "djlint",
                "stylua",
                "black",
                "flake8",
            },
        },
    },
}
